### ISSUE TITLE
Update docker-compose.yml for Dionaea for HTTP/HTTPS

### ISSUE THREAD

**Issue by dindoliboon** [CommunityHoneyNetwork/CommunityHoneyNetwork.github.io#2]
Hi,

The docker-compose.yml for Dionaea, under "Building and Deploying Dionaea" lists HTTP as "80:8080" and HTTPS as "443:8443".

However, stingar/dionaea:latest is listening to "80:80" for HTTP, and "443:443" for HTTPS out-of-the-box.

Updated docker-compose.yml:
```yml
version: '2'
services:
  dionaea:
    image: stingar/dionaea:latest
    volumes:
      - ./dionaea.sysconfig:/etc/default/dionaea
      - ./dionaea:/etc/dionaea
      - ./dionaea/services-available/:/opt/dionaea/etc/dionaea/services-enabled/
    ports:
      - "21:21"
      - "23:23"
      - "53:53"
      - "69:69"
      - "80:80"
      - "123:123"
      - "135:135"
      - "443:443"
      - "445:445"
      - "1433:1433"
      - "1723:1723"
      - "1883:1883"
      - "1900:1900"
      - "3306:3306"
      - "5000:5000"
      - "5060:5060"
      - "5061:5061"
      - "11211:11211"
      - "27017:27017"
```

Tested against Docker image stingar/dionaea:latest, image ID 9e619da97090.

Thanks!
